version: "3.8"
name: evohome
services:
  db:
    image: mysql:8.4
    platform: linux/x86_64
    restart: always
    ports:
      - "3100:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: h65TPPkQNzXVEgWUGTMhTT
      MYSQL_DATABASE: evohome-db
      MYSQL_USER: evohome-db-user
      MYSQL_PASSWORD: evohome-db-password
    command:
      - --character-set-server
      - utf8mb4
      - --collation-server
      - utf8mb4_unicode_ci
  migration:
    image: migration:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    entrypoint: [ "npm", "run", "migration:migrate" ]
  api:
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
